//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRegistration.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Client
    {
        [RegularExpression(@"^([0-9a-zA-Z]([\+\-_\.][0-9a-zA-Z]+)*)+@(([0-9a-zA-Z][-\w]*[0-9a-zA-Z]*\.)+[a-zA-Z0-9]{2,3})$",
         ErrorMessage = "Please provide valid email id")]
        [Required(ErrorMessage = "Please provide Email", AllowEmptyStrings = false)]
        public string email { get; set; }
        [Required(ErrorMessage = "Please provide Full Name", AllowEmptyStrings = false)]
        public string fullName { get; set; }
        [Required(ErrorMessage = "Please provide Address", AllowEmptyStrings = false)]
        public string address { get; set; }
        [Required(ErrorMessage = "Please provide Age", AllowEmptyStrings = false)]
        public Nullable<int> age { get; set; }
        [Required(ErrorMessage = "Please provide Phone", AllowEmptyStrings = false)]
        public string phone { get; set; }
    }
}
