//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRegistration.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Register
    {
        [Required(ErrorMessage = "Please Enter Your Id", AllowEmptyStrings = false)]
        public int Id { get; set; }
        [Required(ErrorMessage = "Enter GuestNumber Please", AllowEmptyStrings = false)]
        public Nullable<int> guestNumber { get; set; }
        [Required(ErrorMessage = "Enter Your Payment Please", AllowEmptyStrings = false)]
        public Nullable<double> paymentAmount { get; set; }
        [Required(ErrorMessage = "Enter Event Name To Register", AllowEmptyStrings = false)]
        public string eventName { get; set; }
        [Required(ErrorMessage = "Enter Email ID To Register Event", AllowEmptyStrings = false)]
        public string email { get; set; }
    }
}
